version: "3.9"

services:
  morphologiacal:
    restart: always
    build:
      context: .
    container_name: python_morphological
    ports:
      - "8000:8000"
    command: >
      bash -c "gunicorn -b 0.0.0.0:8000 morph:app"
